language: ruby
env:
  - CC_TEST_REPORTER_ID=5306e7c3069bd3fef06f717d679f41e969e13bb05efef5bbe1fd781043b0c117
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
before_install:
  - gem update --system
  - gem install bundler
  - bundle install --jobs 10 --redownload --path=${BUNDLE_PATH:-vendor/bundle}
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - USER=travis bundle exec rspec --format documentation
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - if [[ "$TRAVIS_TEST_RESULT" == 0 && "$(ruby --version)" =~ '2.7' ]]; then ./cc-test-reporter format-coverage -t simplecov coverage/.resultset.json; ./cc-test-reporter upload-coverage; fi 
cache: bundler
