language: ruby
env:
  - CODECLIMATE_REPO_TOKEN=5306e7c3069bd3fef06f717d679f41e969e13bb05efef5bbe1fd781043b0c117
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
before_install:
  - gem install bundler --no-ri --no-rdoc
after_success:
  - codeclimate-test-reporter
script: rake
notifications:
  email:
    recipients:
      - kigster@gmail.com
    on_success: change
    on_failure: always
